version: '3.1'
services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file: enviroments/prod.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    
  backend:
    container_name: backend
    image: santlink/backend:djangoApp
    restart: always
    env_file: enviroments/prod.env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  database:
  