apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: backend
  name: backend
  namespace: djangoapp
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: backend
  type: LoadBalancer