version: '3.1'
services:
  db:
    image: postgres:14
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    
  backend:
    build:
      context: app/
      dockerfile: Dockerfile
    container_name: backend
    command: sh -c "python3 manage.py makemigrations && 
                    python3 manage.py migrate && 
                    python3 manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: app/frontend/
      dockerfile: Dockerfile
    container_name: frontend
    command: sh -c "npm run start"
    volumes:
    - ./app/frontend:/usr/src/app
    ports:
    - "3000:3000"

volumes:
  database:
  