version: '3.1'
services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file: prod.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  frontend-build:
    build:
      context: app/frontend/
      dockerfile: Dockerfile
    container_name: frontend
    env_file: prod.env
    volumes:
    - ./app:/usr/src/app
    command: sh -c "cd frontend/ && npm run build"
    
  backend:
    build:
      context: app/
      dockerfile: Dockerfile.prod
    container_name: backend
    volumes:
      - ./app:/usr/src/app
    command: sh -c "sleep 150s
                    python3 manage.py makemigrations && 
                    python3 manage.py migrate && 
                    python3 manage.py collectstatic --noinput &&
                    gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    env_file: prod.env
    depends_on:
      - frontend-build
      - db
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - ./app:/static
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  database:
  