version: '3.1'
services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file: .prod.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    
  backend:
    build:
      context: app/
      dockerfile: Dockerfile.prod
    container_name: backend
    command: sh -c "python3 manage.py makemigrations && 
                    python3 manage.py migrate && 
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    env_file: .prod.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: app/frontend/
      dockerfile: Dockerfile
    container_name: frontend
    command: sh -c "npm run --prefix ./frontend start"
    ports:
    - "3000:3000"

volumes:
  database:
  